#Config-Server

#configure eureka client
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka/
      
     
     
 #Book
 book:
   name:  KBCSS-Book
   title: KBCSS-Title
   isbn:  KBCSS-ISBN
